#!/usr/bin/env bash
cd $HOME/DOB
install() {
rm -rf $HOME/.telegram-cli
 apt-get update -y
 apt-get upgrade -y
 apt-get install software-properties-common -y
 add-apt-repository ppa:ubuntu-toolchain-r/test -y
 luarocks install luasocket
 luarocks install luasec
 luarocks install redis-lua
 luarocks install Lua-cURL
 service redis-server start
 apt-get update -y
 apt-get install g++-4.7 -y c++-4.7
 apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y
 apt-get install screen -y
 apt-get install libstdc++6 -y
 apt-get install lua-lgi -y
 apt-get install libnotify-dev -y
 chmod +x tg
lua DOB.lua
}
if [ "$1" = "install" ]; then
install
else
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
sudo chmod +x tg
DOB.lua
fi
